### ISSUE TITLE
Sound stuttering on Android

### ISSUE THREAD

**Issue by jefvel** [Kode/Kore#141] opened 2017-01-22 01:35 UTC
When starting an application on android there's a chance for all sounds to seemingly play at half speed, sounding very stuttery. It usually stops after the application has been restarted.

Test it with this repository:  https://github.com/jefvel/kha-tests/tree/audio-test

Build, run, and touch the screen for sounds. It should make a single click noise. Close it completely and start up again. From time to time it will sound like two clicks, or straight up crash on startup.

**Comment by tcdude** [comment] 2020-06-08 22:13
I'm unable to reproduce this issue on both a Samsung SM-G930F and Fairphone FP2. Neither did it crash nor did it stutter, play at half speed or sound like two clicks after several attempts of running, touching and every time closing completely.

I had to modify your Main.hx to get it to actually compile / run.

Can you still reproduce the issue with up to date versions of Kinc / Kha?

**Comment by RobDangerous** [comment] 2022-12-05 22:08
Hm, this was probably fixed when we switched to Android's C++-audio-API.

**Closed as completed by RobDangerous** 2022-12-05 22:08 UTC
